/* eslint-disable @typescript-eslint/no-explicit-any */
import { CanvasElement } from './LumiseProductDesigner';

export interface ImagePlaceholderConfig {
  x: number;
  y: number;
  width: number;
  height: number;
  fit: 'contain' | 'cover';
  filter?: string;
  border?: string;
  borderRadius?: number;
  boxShadow?: string;
  aspectRatio?: number;
}

export interface SafePrintAreaConfig {
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface SmartPodTemplate {
  id: string;
  name: string;
  category: 't-shirts' | 'phone-covers' | 'coffee-mugs' | 'both';
  code: string;
  desc: string;
  badge: string;
  thumbnailUrl: string;
  defaultFont: string;
  defaultTextColor: string;
  safePrintArea: SafePrintAreaConfig;
  imagePlaceholder: ImagePlaceholderConfig;
  defaultLayers: CanvasElement[];
}

export const SMART_POD_TEMPLATES: SmartPodTemplate[] = [
  // ==========================================
  // APPAREL & GENERAL TEMPLATES (1-10)
  // ==========================================

  // 1. MINIMAL
  {
    id: 'minimal',
    name: 'Minimal',
    category: 'both',
    code: 'SMART-MIN-01',
    desc: 'Small centered image with generous clean white spacing & subtle caption',
    badge: 'POPULAR',
    thumbnailUrl: '/pod/pod_tmpl_minimal.png',
    defaultFont: 'Montserrat',
    defaultTextColor: '#0F172A',
    safePrintArea: { x: 135, y: 105, width: 210, height: 290 },
    imagePlaceholder: {
      x: 165,
      y: 135,
      width: 150,
      height: 150,
      fit: 'contain',
      border: '1px dashed #64748B',
      borderRadius: 4,
    },
    defaultLayers: [
      {
        id: 'layer-img-placeholder',
        type: 'image',
        name: 'Auto-Snap Photo',
        x: 165,
        y: 135,
        width: 150,
        height: 150,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isHidden: false,
        border: '1px dashed #64748B',
        borderRadius: 4,
        imageUrl: '',
      },
      {
        id: 'layer-txt-sub',
        type: 'text',
        name: 'Minimal Caption',
        text: 'LESS IS MORE',
        fontFamily: 'Montserrat',
        fontSize: 16,
        fontWeight: 'bold',
        letterSpacing: 4,
        color: '#0F172A',
        textAlign: 'center',
        x: 140,
        y: 295,
        width: 200,
        height: 30,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isHidden: false,
      },
      {
        id: 'layer-dec-line',
        type: 'shape',
        shapeType: 'rectangle',
        name: 'Minimalist Line (Locked)',
        fillColor: '#38BDF8',
        strokeColor: '#38BDF8',
        strokeWidth: 1,
        x: 210,
        y: 330,
        width: 60,
        height: 2,
        rotation: 0,
        opacity: 1,
        isLocked: true,
        isHidden: false,
      },
    ],
  },

  // 2. TYPOGRAPHY
  {
    id: 'typography',
    name: 'Typography',
    category: 'both',
    code: 'SMART-TYPO-02',
    desc: 'Large bold headline with image beneath and structured subtitle',
    badge: 'TRENDING',
    thumbnailUrl: '/pod/pod_tmpl_typography.png',
    defaultFont: 'Bebas Neue',
    defaultTextColor: '#0284C7',
    safePrintArea: { x: 135, y: 105, width: 210, height: 290 },
    imagePlaceholder: {
      x: 155,
      y: 150,
      width: 170,
      height: 160,
      fit: 'cover',
      border: '1px dashed #0284C7',
      borderRadius: 4,
    },
    defaultLayers: [
      {
        id: 'layer-txt-head',
        type: 'text',
        name: 'Bold Title Headline',
        text: 'BOLD CREATIVE',
        fontFamily: 'Bebas Neue',
        fontSize: 34,
        fontWeight: 'bold',
        letterSpacing: 2,
        color: '#0284C7',
        textAlign: 'center',
        x: 140,
        y: 110,
        width: 200,
        height: 40,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isHidden: false,
      },
      {
        id: 'layer-img-placeholder',
        type: 'image',
        name: 'Auto-Snap Photo',
        x: 155,
        y: 150,
        width: 170,
        height: 160,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isHidden: false,
        border: '1px dashed #0284C7',
        borderRadius: 4,
        imageUrl: '',
      },
      {
        id: 'layer-txt-sub',
        type: 'text',
        name: 'Studio Subtitle',
        text: 'EST. 2026 • STUDIO EDITION',
        fontFamily: 'Inter',
        fontSize: 11,
        letterSpacing: 2,
        color: '#94A3B8',
        textAlign: 'center',
        x: 140,
        y: 320,
        width: 200,
        height: 25,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isHidden: false,
      },
    ],
  },

  // 3. VINTAGE
  {
    id: 'vintage',
    name: 'Vintage',
    category: 'both',
    code: 'SMART-VINT-03',
    desc: 'Distressed overlay frame, warm faded sepia filter, and retro typography',
    badge: 'RETRO',
    thumbnailUrl: '/pod/pod_tmpl_vintage.png',
    defaultFont: 'Playfair Display',
    defaultTextColor: '#D97706',
    safePrintArea: { x: 135, y: 105, width: 210, height: 290 },
    imagePlaceholder: {
      x: 155,
      y: 140,
      width: 170,
      height: 160,
      fit: 'cover',
      filter: 'sepia(0.55) contrast(1.15)',
      border: '2px solid #D97706',
      borderRadius: 4,
    },
    defaultLayers: [
      {
        id: 'layer-txt-heritage',
        type: 'text',
        name: 'Heritage Banner',
        text: '★ AUTHENTIC HERITAGE ★',
        fontFamily: 'Playfair Display',
        fontStyle: 'italic',
        fontSize: 14,
        color: '#D97706',
        textAlign: 'center',
        x: 140,
        y: 110,
        width: 200,
        height: 30,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isHidden: false,
      },
      {
        id: 'layer-img-placeholder',
        type: 'image',
        name: 'Auto-Snap Photo',
        x: 155,
        y: 140,
        width: 170,
        height: 160,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isHidden: false,
        filter: 'sepia(0.55) contrast(1.15)',
        border: '2px solid #D97706',
        borderRadius: 4,
        imageUrl: '',
      },
      {
        id: 'layer-txt-vintage-title',
        type: 'text',
        name: 'Vintage Headline',
        text: 'VINTAGE 1989',
        fontFamily: 'Oswald',
        fontSize: 26,
        fontWeight: 'bold',
        letterSpacing: 2,
        color: '#D97706',
        textAlign: 'center',
        x: 140,
        y: 310,
        width: 200,
        height: 35,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isHidden: false,
      },
    ],
  },

  // 4. ANIME
  {
    id: 'anime',
    name: 'Anime',
    category: 'both',
    code: 'SMART-ANM-04',
    desc: 'Comic-style dynamic poster frame, neon outlines, and Japanese title',
    badge: 'HOT',
    thumbnailUrl: '/pod/pod_tmpl_anime.png',
    defaultFont: 'Orbitron',
    defaultTextColor: '#EF4444',
    safePrintArea: { x: 135, y: 105, width: 210, height: 290 },
    imagePlaceholder: {
      x: 150,
      y: 140,
      width: 180,
      height: 160,
      fit: 'cover',
      filter: 'contrast(1.3) saturate(1.4)',
      border: '2px solid #EF4444',
      borderRadius: 6,
    },
    defaultLayers: [
      {
        id: 'layer-txt-anime-head',
        type: 'text',
        name: 'Anime Title',
        text: 'SHINOBI SPIRIT // 忍',
        fontFamily: 'Orbitron',
        fontWeight: 'bold',
        fontSize: 22,
        color: '#EF4444',
        textAlign: 'center',
        x: 140,
        y: 110,
        width: 200,
        height: 30,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isHidden: false,
      },
      {
        id: 'layer-img-placeholder',
        type: 'image',
        name: 'Auto-Snap Photo',
        x: 150,
        y: 140,
        width: 180,
        height: 160,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isHidden: false,
        filter: 'contrast(1.3) saturate(1.4)',
        border: '2px solid #EF4444',
        borderRadius: 6,
        imageUrl: '',
      },
      {
        id: 'layer-txt-sub',
        type: 'text',
        name: 'Cyber Subtitle',
        text: 'OVERDRIVE POWER 100%',
        fontFamily: 'Orbitron',
        fontSize: 10,
        letterSpacing: 2,
        color: '#22D3EE',
        textAlign: 'center',
        x: 140,
        y: 310,
        width: 200,
        height: 25,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isHidden: false,
      },
    ],
  },

  // 5. SPORTS
  {
    id: 'sports',
    name: 'Sports',
    category: 'both',
    code: 'SMART-SPT-05',
    desc: 'Athletic jersey styling with squad numbers, varsity typography, and activewear stripes',
    badge: 'NEW',
    thumbnailUrl: '/pod/pod_tmpl_sports.png',
    defaultFont: 'Oswald',
    defaultTextColor: '#EF4444',
    safePrintArea: { x: 135, y: 105, width: 210, height: 290 },
    imagePlaceholder: {
      x: 150,
      y: 145,
      width: 180,
      height: 140,
      fit: 'cover',
      border: '2px solid #EF4444',
      borderRadius: 4,
    },
    defaultLayers: [
      {
        id: 'layer-txt-arch',
        type: 'text',
        name: 'Varsity Arch',
        text: 'CHAMPIONS',
        fontFamily: 'Oswald',
        fontWeight: 'bold',
        fontSize: 32,
        color: '#EF4444',
        textAlign: 'center',
        x: 140,
        y: 110,
        width: 200,
        height: 35,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isHidden: false,
      },
      {
        id: 'layer-img-placeholder',
        type: 'image',
        name: 'Auto-Snap Photo',
        x: 150,
        y: 145,
        width: 180,
        height: 140,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isHidden: false,
        border: '2px solid #EF4444',
        borderRadius: 4,
        imageUrl: '',
      },
      {
        id: 'layer-txt-number',
        type: 'text',
        name: 'Jersey Number',
        text: '07',
        fontFamily: 'Bebas Neue',
        fontSize: 36,
        fontWeight: 'bold',
        color: '#111827',
        textAlign: 'center',
        x: 210,
        y: 295,
        width: 60,
        height: 40,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isHidden: false,
      },
    ],
  },

  // 6. BIRTHDAY
  {
    id: 'birthday',
    name: 'Birthday',
    category: 'both',
    code: 'SMART-BDAY-06',
    desc: 'Colorful celebratory frame with party scripts, confetti stars, and milestone banner',
    badge: 'PARTY',
    thumbnailUrl: '/pod/pod_tmpl_birthday.png',
    defaultFont: 'Pacifico',
    defaultTextColor: '#EC4899',
    safePrintArea: { x: 135, y: 105, width: 210, height: 290 },
    imagePlaceholder: {
      x: 155,
      y: 140,
      width: 170,
      height: 150,
      fit: 'cover',
      border: '3px dashed #F59E0B',
      borderRadius: 8,
    },
    defaultLayers: [
      {
        id: 'layer-txt-bday-head',
        type: 'text',
        name: 'Party Header',
        text: 'Happy Birthday',
        fontFamily: 'Pacifico',
        fontSize: 28,
        color: '#EC4899',
        textAlign: 'center',
        x: 140,
        y: 110,
        width: 200,
        height: 35,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isHidden: false,
      },
      {
        id: 'layer-img-placeholder',
        type: 'image',
        name: 'Auto-Snap Photo',
        x: 155,
        y: 140,
        width: 170,
        height: 150,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isHidden: false,
        border: '3px dashed #F59E0B',
        borderRadius: 8,
        imageUrl: '',
      },
      {
        id: 'layer-txt-sub',
        type: 'text',
        name: 'Celebration Banner',
        text: '✨ CELEBRATE IN STYLE ✨',
        fontFamily: 'Poppins',
        fontWeight: 'bold',
        fontSize: 11,
        color: '#F59E0B',
        textAlign: 'center',
        x: 140,
        y: 305,
        width: 200,
        height: 30,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isHidden: false,
      },
    ],
  },

  // 7. GAMING
  {
    id: 'gaming',
    name: 'Gaming',
    category: 'both',
    code: 'SMART-GAM-07',
    desc: 'Cyberpunk HUD lines, RGB controller badge, and level-up pixel aesthetics',
    badge: 'GAMER',
    thumbnailUrl: '/pod/pod_tmpl_gaming.png',
    defaultFont: 'Orbitron',
    defaultTextColor: '#38BDF8',
    safePrintArea: { x: 135, y: 105, width: 210, height: 290 },
    imagePlaceholder: {
      x: 155,
      y: 140,
      width: 170,
      height: 150,
      fit: 'cover',
      filter: 'contrast(1.3) saturate(1.3)',
      border: '2px solid #38BDF8',
      borderRadius: 6,
    },
    defaultLayers: [
      {
        id: 'layer-txt-game-head',
        type: 'text',
        name: 'Gamer Title',
        text: 'LEVEL UP // 99',
        fontFamily: 'Orbitron',
        fontWeight: 'bold',
        fontSize: 26,
        color: '#38BDF8',
        textAlign: 'center',
        x: 140,
        y: 110,
        width: 200,
        height: 35,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isHidden: false,
      },
      {
        id: 'layer-img-placeholder',
        type: 'image',
        name: 'Auto-Snap Photo',
        x: 155,
        y: 140,
        width: 170,
        height: 150,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isHidden: false,
        filter: 'contrast(1.3) saturate(1.3)',
        border: '2px solid #38BDF8',
        borderRadius: 6,
        imageUrl: '',
      },
      {
        id: 'layer-txt-sub',
        type: 'text',
        name: 'Rank Subtitle',
        text: '✦ ELITE RANK SSS ✦',
        fontFamily: 'Orbitron',
        fontSize: 10,
        letterSpacing: 2,
        color: '#F43F5E',
        textAlign: 'center',
        x: 140,
        y: 310,
        width: 200,
        height: 25,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isHidden: false,
      },
    ],
  },

  // 8. FLORAL
  {
    id: 'floral',
    name: 'Floral',
    category: 'both',
    code: 'SMART-FLR-08',
    desc: 'Full-print tropical blue floral botanical blossom patterns',
    badge: 'AESTHETIC',
    thumbnailUrl: '/pod/pod_tmpl_floral.png',
    defaultFont: 'Dancing Script',
    defaultTextColor: '#38BDF8',
    safePrintArea: { x: 135, y: 105, width: 210, height: 290 },
    imagePlaceholder: {
      x: 155,
      y: 140,
      width: 170,
      height: 150,
      fit: 'cover',
      border: '2px solid #38BDF8',
      borderRadius: 12,
    },
    defaultLayers: [
      {
        id: 'layer-txt-floral-head',
        type: 'text',
        name: 'Floral Title',
        text: 'Bloom & Glow',
        fontFamily: 'Dancing Script',
        fontSize: 32,
        color: '#38BDF8',
        textAlign: 'center',
        x: 140,
        y: 110,
        width: 200,
        height: 35,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isHidden: false,
      },
      {
        id: 'layer-img-placeholder',
        type: 'image',
        name: 'Auto-Snap Photo',
        x: 155,
        y: 140,
        width: 170,
        height: 150,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isHidden: false,
        border: '2px solid #38BDF8',
        borderRadius: 12,
        imageUrl: '',
      },
      {
        id: 'layer-txt-sub',
        type: 'text',
        name: 'Floral Tagline',
        text: 'BOTANICAL EDITION',
        fontFamily: 'Playfair Display',
        fontSize: 10,
        letterSpacing: 2,
        color: '#7DD3FC',
        textAlign: 'center',
        x: 140,
        y: 310,
        width: 200,
        height: 25,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isHidden: false,
      },
    ],
  },

  // 9. STREETWEAR
  {
    id: 'streetwear',
    name: 'Streetwear',
    category: 'both',
    code: 'SMART-STR-09',
    desc: 'Urban box logo, brutalist typography, and contemporary street aesthetic',
    badge: 'URBAN',
    thumbnailUrl: '/pod/pod_tmpl_streetwear.png',
    defaultFont: 'Bebas Neue',
    defaultTextColor: '#EF4444',
    safePrintArea: { x: 135, y: 105, width: 210, height: 290 },
    imagePlaceholder: {
      x: 150,
      y: 140,
      width: 180,
      height: 150,
      fit: 'cover',
      border: '3px solid #111827',
      borderRadius: 0,
    },
    defaultLayers: [
      {
        id: 'layer-txt-street-head',
        type: 'text',
        name: 'Streetwear Logo',
        text: 'OFF-LIMITS // TOKYO',
        fontFamily: 'Bebas Neue',
        fontSize: 30,
        letterSpacing: 2,
        color: '#EF4444',
        textAlign: 'center',
        x: 140,
        y: 110,
        width: 200,
        height: 35,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isHidden: false,
      },
      {
        id: 'layer-img-placeholder',
        type: 'image',
        name: 'Auto-Snap Photo',
        x: 150,
        y: 140,
        width: 180,
        height: 150,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isHidden: false,
        border: '3px solid #111827',
        borderRadius: 0,
        imageUrl: '',
      },
      {
        id: 'layer-txt-sub',
        type: 'text',
        name: 'Raw Apparel Code',
        text: 'RAW APPAREL CO. • NO. 09',
        fontFamily: 'Montserrat',
        fontWeight: 'bold',
        fontSize: 10,
        letterSpacing: 2,
        color: '#111827',
        textAlign: 'center',
        x: 140,
        y: 310,
        width: 200,
        height: 25,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isHidden: false,
      },
    ],
  },

  // 10. PHOTO PRINT
  {
    id: 'photo-print',
    name: 'Photo Print',
    category: 'both',
    code: 'SMART-PHT-10',
    desc: 'Polaroid snapshot frame with custom caption area stamp and high-res print',
    badge: 'PHOTO',
    thumbnailUrl: '/pod/pod_phone_case.png',
    defaultFont: 'Poppins',
    defaultTextColor: '#0F172A',
    safePrintArea: { x: 135, y: 105, width: 210, height: 290 },
    imagePlaceholder: {
      x: 145,
      y: 115,
      width: 190,
      height: 200,
      fit: 'cover',
      border: '3px solid #FFFFFF',
      borderRadius: 4,
      boxShadow: '0 4px 14px rgba(0,0,0,0.15)',
    },
    defaultLayers: [
      {
        id: 'layer-img-placeholder',
        type: 'image',
        name: 'Auto-Snap Photo',
        x: 145,
        y: 115,
        width: 190,
        height: 200,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isHidden: false,
        border: '3px solid #FFFFFF',
        borderRadius: 4,
        boxShadow: '0 4px 14px rgba(0,0,0,0.15)',
        imageUrl: '',
      },
      {
        id: 'layer-txt-stamp',
        type: 'text',
        name: 'Polaroid Caption',
        text: 'PERSONAL MOMENTS • 2026',
        fontFamily: 'Poppins',
        fontSize: 12,
        letterSpacing: 2,
        color: '#0F172A',
        textAlign: 'center',
        x: 140,
        y: 330,
        width: 200,
        height: 25,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isHidden: false,
      },
    ],
  },

  // ==========================================
  // COFFEE MUG DEDICATED TEMPLATES (11-16)
  // ==========================================

  // 11. MUG PHOTO WRAP
  {
    id: 'mug-photo-wrap',
    name: 'Photo Wrap',
    category: 'coffee-mugs',
    code: 'MUG-PHT-01',
    desc: '360° panoramic high-resolution wrap-around photo frame',
    badge: 'BESTSELLER',
    thumbnailUrl: '/pod/pod_mugs.png',
    defaultFont: 'Poppins',
    defaultTextColor: '#111827',
    safePrintArea: { x: 130, y: 130, width: 200, height: 220 },
    imagePlaceholder: {
      x: 140,
      y: 140,
      width: 180,
      height: 170,
      fit: 'cover',
      border: '2px solid #E5E7EB',
      borderRadius: 4,
    },
    defaultLayers: [
      {
        id: 'layer-img-placeholder',
        type: 'image',
        name: 'Wrap Photo Print',
        x: 140,
        y: 140,
        width: 180,
        height: 170,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isHidden: false,
        border: '2px solid #E5E7EB',
        borderRadius: 4,
        imageUrl: '',
      },
      {
        id: 'layer-txt-sub',
        type: 'text',
        name: 'Mug Caption',
        text: 'SUNSHINE & COFFEE',
        fontFamily: 'Poppins',
        fontSize: 14,
        fontWeight: 'bold',
        letterSpacing: 3,
        color: '#111827',
        textAlign: 'center',
        x: 130,
        y: 320,
        width: 200,
        height: 25,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isHidden: false,
      },
    ],
  },

  // 12. MUG FLORAL BLOSSOM
  {
    id: 'mug-floral',
    name: 'Floral Blossom',
    category: 'coffee-mugs',
    code: 'MUG-FLR-02',
    desc: 'Botanical coffee floral watercolor garland and cursive lettering',
    badge: 'POPULAR',
    thumbnailUrl: '/pod/pod_tmpl_floral.png',
    defaultFont: 'Dancing Script',
    defaultTextColor: '#0284C7',
    safePrintArea: { x: 130, y: 130, width: 200, height: 220 },
    imagePlaceholder: {
      x: 150,
      y: 155,
      width: 160,
      height: 140,
      fit: 'cover',
      border: '2px solid #38BDF8',
      borderRadius: 12,
    },
    defaultLayers: [
      {
        id: 'layer-txt-head',
        type: 'text',
        name: 'Morning Script',
        text: 'Morning Bloom',
        fontFamily: 'Dancing Script',
        fontSize: 28,
        color: '#0284C7',
        textAlign: 'center',
        x: 130,
        y: 125,
        width: 200,
        height: 35,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isHidden: false,
      },
      {
        id: 'layer-img-placeholder',
        type: 'image',
        name: 'Floral Artwork',
        x: 150,
        y: 155,
        width: 160,
        height: 140,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isHidden: false,
        border: '2px solid #38BDF8',
        borderRadius: 12,
        imageUrl: '',
      },
      {
        id: 'layer-txt-sub',
        type: 'text',
        name: 'Espresso Subtitle',
        text: 'FRESH ROAST • DAILY BREW',
        fontFamily: 'Inter',
        fontSize: 10,
        letterSpacing: 2,
        color: '#64748B',
        textAlign: 'center',
        x: 130,
        y: 310,
        width: 200,
        height: 20,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isHidden: false,
      },
    ],
  },

  // 13. MUG MINIMAL MONOGRAM
  {
    id: 'mug-minimal',
    name: 'Minimal Monogram',
    category: 'coffee-mugs',
    code: 'MUG-MIN-03',
    desc: 'Clean initial monogram, modern geometric line, and single badge',
    badge: 'TRENDING',
    thumbnailUrl: '/pod/pod_tmpl_minimal.png',
    defaultFont: 'Montserrat',
    defaultTextColor: '#111827',
    safePrintArea: { x: 130, y: 130, width: 200, height: 220 },
    imagePlaceholder: {
      x: 160,
      y: 150,
      width: 140,
      height: 140,
      fit: 'contain',
      border: '1px dashed #94A3B8',
      borderRadius: 4,
    },
    defaultLayers: [
      {
        id: 'layer-img-placeholder',
        type: 'image',
        name: 'Center Emblem',
        x: 160,
        y: 150,
        width: 140,
        height: 140,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isHidden: false,
        border: '1px dashed #94A3B8',
        borderRadius: 4,
        imageUrl: '',
      },
      {
        id: 'layer-txt-sub',
        type: 'text',
        name: 'Monogram Label',
        text: 'COFFEE FIRST',
        fontFamily: 'Montserrat',
        fontSize: 14,
        fontWeight: 'bold',
        letterSpacing: 4,
        color: '#111827',
        textAlign: 'center',
        x: 130,
        y: 305,
        width: 200,
        height: 25,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isHidden: false,
      },
    ],
  },

  // 14. MUG BIRTHDAY CELEBRATION
  {
    id: 'mug-birthday',
    name: 'Birthday Celebration',
    category: 'coffee-mugs',
    code: 'MUG-BDAY-04',
    desc: 'Celebratory birthday gift mug with festive script and stars',
    badge: 'GIFT',
    thumbnailUrl: '/pod/pod_tmpl_birthday.png',
    defaultFont: 'Pacifico',
    defaultTextColor: '#EC4899',
    safePrintArea: { x: 130, y: 130, width: 200, height: 220 },
    imagePlaceholder: {
      x: 150,
      y: 155,
      width: 160,
      height: 140,
      fit: 'cover',
      border: '3px dashed #F59E0B',
      borderRadius: 8,
    },
    defaultLayers: [
      {
        id: 'layer-txt-head',
        type: 'text',
        name: 'Birthday Script',
        text: 'Happy Birthday!',
        fontFamily: 'Pacifico',
        fontSize: 26,
        color: '#EC4899',
        textAlign: 'center',
        x: 130,
        y: 125,
        width: 200,
        height: 35,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isHidden: false,
      },
      {
        id: 'layer-img-placeholder',
        type: 'image',
        name: 'Gift Photo',
        x: 150,
        y: 155,
        width: 160,
        height: 140,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isHidden: false,
        border: '3px dashed #F59E0B',
        borderRadius: 8,
        imageUrl: '',
      },
      {
        id: 'layer-txt-sub',
        type: 'text',
        name: 'Wish Tagline',
        text: '✨ SIP WITH A SMILE ✨',
        fontFamily: 'Poppins',
        fontWeight: 'bold',
        fontSize: 11,
        color: '#F59E0B',
        textAlign: 'center',
        x: 130,
        y: 310,
        width: 200,
        height: 25,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isHidden: false,
      },
    ],
  },

  // 15. MUG CORPORATE LOGO
  {
    id: 'mug-corporate',
    name: 'Corporate Logo',
    category: 'coffee-mugs',
    code: 'MUG-CORP-05',
    desc: 'Crisp corporate brand badge placement and company slogan',
    badge: 'BUSINESS',
    thumbnailUrl: '/pod/pod_mugs.png',
    defaultFont: 'Bebas Neue',
    defaultTextColor: '#1E40AF',
    safePrintArea: { x: 130, y: 130, width: 200, height: 220 },
    imagePlaceholder: {
      x: 150,
      y: 145,
      width: 160,
      height: 150,
      fit: 'contain',
      border: '1px solid #93C5FD',
      borderRadius: 4,
    },
    defaultLayers: [
      {
        id: 'layer-img-placeholder',
        type: 'image',
        name: 'Company Logo',
        x: 150,
        y: 145,
        width: 160,
        height: 150,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isHidden: false,
        border: '1px solid #93C5FD',
        borderRadius: 4,
        imageUrl: '',
      },
      {
        id: 'layer-txt-sub',
        type: 'text',
        name: 'Company Slogan',
        text: 'INNOVATION & EXCELLENCE',
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fontSize: 10,
        letterSpacing: 2,
        color: '#1E40AF',
        textAlign: 'center',
        x: 130,
        y: 310,
        width: 200,
        height: 20,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isHidden: false,
      },
    ],
  },

  // 16. MUG INSPIRATIONAL QUOTE
  {
    id: 'mug-quote',
    name: 'Inspirational Quote',
    category: 'coffee-mugs',
    code: 'MUG-QUT-06',
    desc: 'Bold retro coffee quote with aesthetic lettering',
    badge: 'POPULAR',
    thumbnailUrl: '/pod/pod_tmpl_typography.png',
    defaultFont: 'Bebas Neue',
    defaultTextColor: '#D97706',
    safePrintArea: { x: 130, y: 130, width: 200, height: 220 },
    imagePlaceholder: {
      x: 150,
      y: 155,
      width: 160,
      height: 135,
      fit: 'cover',
      border: '1px dashed #D97706',
      borderRadius: 4,
    },
    defaultLayers: [
      {
        id: 'layer-txt-head',
        type: 'text',
        name: 'Quote Title',
        text: 'BUT FIRST, COFFEE',
        fontFamily: 'Bebas Neue',
        fontSize: 30,
        letterSpacing: 2,
        color: '#D97706',
        textAlign: 'center',
        x: 130,
        y: 125,
        width: 200,
        height: 35,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isHidden: false,
      },
      {
        id: 'layer-img-placeholder',
        type: 'image',
        name: 'Coffee Artwork',
        x: 150,
        y: 155,
        width: 160,
        height: 135,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isHidden: false,
        border: '1px dashed #D97706',
        borderRadius: 4,
        imageUrl: '',
      },
      {
        id: 'layer-txt-sub',
        type: 'text',
        name: 'Motto Subtitle',
        text: 'STAY GROUNDED • DREAM BIG',
        fontFamily: 'Montserrat',
        fontSize: 10,
        letterSpacing: 2,
        color: '#78350F',
        textAlign: 'center',
        x: 130,
        y: 305,
        width: 200,
        height: 20,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isHidden: false,
      },
    ],
  },
];
